#!/bin/bash
. /cs/labs/raananf/yael_vinker/python7-venv/bin/activate
python3.7 create_dng_npy_data.py --root_hdr "/cs/labs/raananf/yael_vinker/dng_collection" --output_hdr "/cs/labs/raananf/yael_vinker/data/log1000_all_hdrplus" --hdr_test_dir "/cs/labs/raananf/yael_vinker/data/test/hdrplus_log1000/hdrplus_log1000" --log_factor 1000
